# AB testing for Grocery Shop

In [2]:
# Importing required libraries
import pandas as pd
from scipy.stats import chi2_contingency, chi2

In [10]:
# Import Data
campaign_data = pd.read_excel("grocery_database.xlsx", sheet_name='campaign_data')

In [11]:
campaign_data

     customer_id  campaign_name campaign_date mailer_type  signup_flag
0             74  delivery_club    2020-07-01     Mailer1            1
1            524  delivery_club    2020-07-01     Mailer1            1
2            607  delivery_club    2020-07-01     Mailer2            1
3            343  delivery_club    2020-07-01     Mailer1            0
4            322  delivery_club    2020-07-01     Mailer2            1
..           ...            ...           ...         ...          ...
865          372  delivery_club    2020-07-01     Mailer2            1
866          104  delivery_club    2020-07-01     Mailer1            1
867          393  delivery_club    2020-07-01     Mailer2            1
868          373  delivery_club    2020-07-01     Control            0
869          712  delivery_club    2020-07-01     Control            0

[870 rows x 5 columns]

In [12]:
# Filtering Data
campaign_data = campaign_data.loc[campaign_data['mailer_type'] != 'Control']

In [13]:
campaign_data

     customer_id  campaign_name campaign_date mailer_type  signup_flag
0             74  delivery_club    2020-07-01     Mailer1            1
1            524  delivery_club    2020-07-01     Mailer1            1
2            607  delivery_club    2020-07-01     Mailer2            1
3            343  delivery_club    2020-07-01     Mailer1            0
4            322  delivery_club    2020-07-01     Mailer2            1
..           ...            ...           ...         ...          ...
863          765  delivery_club    2020-07-01     Mailer2            1
864          466  delivery_club    2020-07-01     Mailer1            1
865          372  delivery_club    2020-07-01     Mailer2            1
866          104  delivery_club    2020-07-01     Mailer1            1
867          393  delivery_club    2020-07-01     Mailer2            1

[711 rows x 5 columns]

In [15]:
# Summarize to get observed frequencies
observed_values = pd.crosstab(campaign_data['mailer_type'], campaign_data['signup_flag']).values
observed_values

array([[252, 123],
       [209, 127]], dtype=int64)

In [16]:
mailer1_signup_rate = 123/(252 + 123)
mailer2_signup_rate = 127/(209 + 127)
print(mailer1_signup_rate, mailer2_signup_rate)

0.328 0.37797619047619047

In [18]:
# State Hypothesis and Set Acceptance Criteria
null_hypothesis = "There is no relationship between mailer type and signup rate. They are independent"
alternate_hypothesis = "There is a relationship between mailer type and signup rate. They are not independent"
acceptance_criteria = 0.05

In [19]:
# Calculate expected frequencies and chi square statistic
chi2_statistic, p_value, dof, expected_values = chi2_contingency(observed_values, correction=False)
print(chi2_statistic, p_value)

1.9414468614812481 0.16351152223398197

In [21]:
# Find the critical value of our test
critical_value = chi2.ppf(1 - acceptance_criteria, dof)
print(critical_value)

3.841458820694124

In [22]:
# Results 
if chi2_statistic >= critical_value:
    print(f"As our chi-square statistic of {chi2_statistic} is higher than our critical value of {critical_value} - we reject the null hypothesis, and conclude that: {alternate_hypothesis}")
else:
    print(f"As our chi-square statistic of {chi2_statistic} is lower than our critical value of {critical_value} - we fail to reject the null hypothesis, and conclude that: {null_hypothesis}")

As our chi-square statistic of 1.9414468614812481 is lower than our critical value of 3.841458820694124 - we fail to reject the null hypothesis, and conclude that: There is no relationship between mailer type and signup rate. They are independent

In [24]:
if p_value <= acceptance_criteria:
    print(f"As our p_value statistic of {p_value} is lower than our acceptance criteria of {acceptance_criteria} - we reject the null hypothesis, and conclude that: {alternate_hypothesis}")
else:
    print(f"As our p_value statistic of {p_value} is higher than our acceptance criteria of {acceptance_criteria} - we fail reject the null hypothesis, and conclude that: {null_hypothesis}")

As our p_value statistic of 0.16351152223398197 is higher than our acceptance criteria of 0.05 - we fail reject the null hypothesis, and conclude that: There is no relationship between mailer type and signup rate. They are independent